### ISSUE TITLE
Support for newer Package Versions

### ISSUE THREAD

**Issue by gro1m** [Arize-ai/client_python#68]
Would be great if the following package versions were supported:

- pandas 2.0.*
- lightgbm 4.0.*

**Comment by fjcasti1** [comment]
Hey @gro1m, sorry for the late response. We are including this in our backlog. We'll notify you when new package versions are supported.

**Comment by fjcasti1** [comment]
Hey @gro1m, included is the updated dependency requirement for pandas 2.x in the [7.8.0 release](https://pypi.org/project/arize/7.8.0/). See [PR](https://github.com/Arize-ai/client_python/pull/73). I'll try to squeeze the other requirement you asked for in a follow up

**Comment by nick-ocurate** [comment]
Hi, there.  We are also trying to incorporate the Arize MimicExplainer package in our workflow.  It would be great if you would also be able to add numpy 1.24.*, as well.  Thank you!

**Comment by fjcasti1** [comment]
Hey @gro1m, will look into numpy and lightgbm in our next release or two. Will notify you

**Comment by fjcasti1** [comment]
Hi @gro1m, in our latest release 7.10.0 we looked at our requirements for the mimic explainer. We now just defer to the requirements of the libraries we use without any other guardrails. Hence, you should be able to use the versions you mentioned above. Please let me know when you do so I can close the issue
https://github.com/Arize-ai/client_python/blob/main/setup.cfg#L45
