### ISSUE TITLE
Async Task Missing dataset_row

### ISSUE THREAD

**Issue by ErikCohenDev** [Arize-ai/client_python#99]
I'm having trouble getting the dataset_row when running an async task.
During debugging it looks that the data is in example but gets lost in `bound_task_args`

it works if I pass 
```python
_output = task(example.dataset_row, **bound_task_args.kwargs)
```

https://github.com/Arize-ai/client_python/blob/e5063dc8cef37720c8a4285b05f3f5f9be7077a7/arize/experimental/datasets/experiments/functions.py#L90

**Comment by arizedatngo** [comment]
fixed, was an input issue. will add to docs to make it more clear the inputs
